### ISSUE TITLE
go client opens 5500 connections to same remote peer.

### ISSUE THREAD

**Issue by Raynos** [uber/tchannel-go#134]
We've noticed that a go production service opens 5k sockets to the same hyperbahn peer.

Not sure why :(

**Comment by prashantv** [comment]
Issue was caused by a client creating many channels, whichwe explicitly warn against in our documentation.

**Comment by Raynos** [comment]
Yep; noticed in code review that it was root cause.

In terms of defence in depth should tchannel connection instances have some kind of 5m / 10m / 30m / whatever timeout on them ? If socket is unused after some time K then just drain().

**Comment by prashantv** [comment]
We should come up with semantics that make sense and implement them across languages. I think the best thing would be for Hyperbahn to have these kinds of timeouts, since it will help all the client libraries, and we can tweak it before implementing it in the clients.
