### ISSUE TITLE
Use separate types for atomics

### ISSUE THREAD

**Issue by prashantv** [uber/tchannel-go#152]
To avoid issues like #143, we should create separate types for atomics to avoid accidentally using them without the atomic operations. E.g.

```go
type AtomicInt32 struct { int32 }

func (i *AtomicInt32) Increment() int32 {
  return i.Add(1)    
}

func (i *AtomicInt32) Add(n int32) {
  return atomic.AddInt32(&i.int32, n)
}

func (i *AtomicInt32) Load() int32() {
  return i.Add(0)
}
```

Since the type will be a struct, it will avoid accidentally incrementing using `++` or passing the value as an argument to a function that expects an `int32` without loading the value atomically.

cc @nomis52

**Comment by akshayjshah** [comment]
@prashantv assuming you'd prefer these to be structs instead of type aliases so we can't mistakenly add to them, right?

**Comment by prashantv** [comment]
Yep, want to make sure you can't use `i++` if `i` is atomic

**Comment by prashantv** [comment]
Fixed by #259

**Comment by prashantv** [comment]
Actually, we should update tchannel-go to use the new package. @akshayjshah

**Comment by akshayjshah** [comment]
Yep, was just taking this in two steps.
