### ISSUE TITLE
Release a 1.0 of tchannel-go

### ISSUE THREAD

**Issue by prashantv** [uber/tchannel-go#166]
We should come up with some sort of release process, and release a 1.0 release.

- [x] Remove TODO.md
- [x] Add CONTRIBUTING.md
- [x] Add LICENSE.md
- [x] Add coveralls support (it should be enabled for our repo)
- [x] Add changelog. Started one in `version` branch, https://github.com/uber/tchannel-go/tree/version
- [x] Update version to `1.0`
- [x] Tag release
- [x] Create a binary release (for thrift-gen, there should be Makefile rules to help with that)

**Comment by mranney** [comment]
I suggest that at this point you just declare 1.0, because we are already using this in production.

**Comment by akshayjshah** [comment]
Point taken, issue updated to reference 1.0
