### ISSUE TITLE
Add a method of removing a peer.

### ISSUE THREAD

**Issue by nomis52** [uber/tchannel-go#184]
We'll need this in order to keep the peer list in sync with  ip:ports obtained from DNS.

Alternatively, we could add DNS resolution & re-resolution to the channel library and avoid the need to manage peers in the application.

**Comment by prashantv** [comment]
I'd like to avoid DNS concerns in tchannel, it's pretty tied to IPv4 addresses in a lot of ways.

I've planned to add a remove method on the PeerList, so that should be pretty easy to add.
