### ISSUE TITLE
Coverage reporting is causing travis to fail

### ISSUE THREAD

**Issue by prashantv** [uber/tchannel-go#215]
Looks like Travis is failing right now:

See failed builds:
https://travis-ci.org/uber/tchannel-go/jobs/106907240

```
goveralls -coverprofile=./build/coverage.out -service=travis-ci
Bad response status from coveralls: 422 - {"message":"Couldn't find a repository matching this job.","error":true}
make: *** [cover_ci] Error 1
The command "make cover_ci" exited with 2.
```

Any ideas what's going on @akshayjshah?

**Comment by akshayjshah** [comment]
Weird - I have no idea. http://status.coveralls.io/#week doesn't show any problems and the current builds are passing.

To me, this looks like a minor coveralls outage. I'm inclined to close and see if the problem reappears later.

**Comment by prashantv** [comment]
Yep, looks like it's not affecting  builds now. It kept failing for a few hours so I wasn't sure if it was something bigger. Can reopen later if it reappaers.
