### ISSUE TITLE
go vet errors will return success exit code

### ISSUE THREAD

**Issue by dansimau** [uber/tchannel-go#223]
The [lint target in the Makefile](https://github.com/uber/tchannel-go/blob/dev/Makefile#L100) captures the output of linting commands to a file and then checks to see if that file is non-zero in length.

However, go vet outputs to stderr, which means the output of this command will never be tee'd to the file. This could lead to go vet errors returning a success exit code.

The fix is to redirect stderr to stdout for go vet:

```shell
@echo "Running go vet"
-go tool vet $(PKGS) 2>&1 | tee -a lint.log
```

**Comment by prashantv** [comment]
Thanks @dansimau, will look into this.
