### ISSUE TITLE
How do I use the _pprof endpoint?

### ISSUE THREAD

**Issue by tiffanycheng** [uber/tchannel-go#434]
There seems to be no documentation on how to tcurl _pprof. Should tchannel services be starting up http servers themselves? With a specific port?

**Comment by prashantv** [comment]
The `_pprof` endpoint expects a HTTP request encapsulated inside of a TChannel request. It requires a proxy that will accept HTTP calls and will envelope them inside of a TChannel request.

Unfortunately the proxy is not built, but it would be very similar to the code in:
https://github.com/uber/tchannel-go/blob/dev/http/http_test.go

Internally, I wanted to start a service that would host the proxy, but I haven't had time to work on that.

**Comment by prashantv** [comment]
Snippet of a HTTP handler to proxy calls over TChannel, used in the internal TChannel pprof proxy:
https://gist.github.com/prashantv/8afc18b58304b855e257cedc84807b9d
