### ISSUE TITLE
Better handling in peer.Connect for host:port mismatches

### ISSUE THREAD

**Issue by prashantv** [uber/tchannel-go#450]
If we create an outbound connection to a peer `127.0.0.1:21300` but it identifies itself as `1.1.1.1:21300`, currently we don't add the connection to a peer under `127.0.0.1:21300`.

If another call is made to the same host:port, we don't find the previous connection (since it's under another peer) and end up creating a new connection.

This ends up causing a large number of connections to be made. Previously, we only added the peer to `127.0.0.1:21300` and we ignored the connection host:port sent in the init req.

**Comment by prashantv** [comment]
Having second thoughts on whether we want to do this and what the right solution is.
 
**Pros:**
 - Makes it harder to accidentally send traffic to the wrong place.
 - Stops clients from advertising to a production Hyperbahn from a local instance. Advertising causes production hyperbahn to try and connect to some `host:port` which isn't valid in production and will fail.

**Cons:**
 - Means tests that interpose relays etc will now fail since the host:port to use for the relay doesn't match the host:port that the remote side is listening on
 - In a tool like `yab` which uses this library, we want it to send requests to the specified host:port regardless of whether there's a tunnel or some TCP relay


**Options:**
1. Go back to pre `1.0.8` behaviour where we add the connection to the peer based on the `hostPort` we connected to rather than the `host:port` the remote side returns.
2. Add an option to the channel to toggle behaviour (strict by default, tests/tools like `yab` can use non-strict)

The current behaviour is not ideal since it allows the connections to go through but then unexpectedly keeps creating new connections.

cc: @blampe @akshayjshah

**Comment by akshayjshah** [comment]
While option #2 appeals to me for its correctness and safety, I think it'll be painful in practice - I'm particularly worried about making clients aware of whether or not they're being relayed.

**Comment by blampe** [comment]
Agree with @akshayjshah. Is the first option prohibitively expensive to implement?

**Comment by prashantv** [comment]
Nope, with either 1 or 2, we would need to support it.

It's a little complicated (a connection may now be in multiple peers), and it means strange things could happen (e.g., advertise to Hyperbahn with a `host:port` that hyperbahn will never be able to connect back to due to tunneling).

However, it's the most compatible with debugging/tooling. I'll add a debug log to catch when this happens, in future maybe we should emit metrics for them.
