### ISSUE TITLE
Add trace tags for rpc

### ISSUE THREAD

**Issue by kriskowal** [uber/tchannel-go#494]
We will produce rpc prefixèd tags in YARPC with the HTTP transport. To do the same with TChannel, we would need to either expose the span on the outbound call response struct, or submit these tags directly. The caller and service tags differ from the peer tag only in that they always express the direction of the call, regardless of whether they are emitted inbound or outbound.

```
        opentracing.Tags{
            "rpc.caller":    treq.Caller,
            "rpc.service":   treq.Service,
            "rpc.encoding":  treq.Encoding,
            "rpc.transport": "http",
        },
```

Whether to submit these tags at all is open for discussion. I expect that they will be useful.

**Comment by prashantv** [comment]
@yurishkuro Should these be standard tags in the OpenTracing world? We can definitely add these tags from TChannel, I think we have all the information available in the tchannel package.

**Comment by yurishkuro** [comment]
We can open an issue proposing those, but "let' wait for three use cases" rule might be applied before it is accepted. 

Also, I am not sure why `caller` and `service` are necessary. On the client side, the caller is already known to the tracer, and the `service` is captured via `peer.service` (on the server side those two are reversed).

**Comment by kriskowal** [comment]
@yurishkuro It is precisely the reversal that makes these tags useful. The peer.service property would not be useful to search for traces that only involve a service specifically in the role of either a caller or a callee.

**Comment by yurishkuro** [comment]
encoding the side in the tag is redundant since it's already known from other data points, e.g. from the `span.kind` (`server` or `client`) tag. A search can be done with an AND condition on two tags.

**Comment by prashantv** [comment]
Closing, if we want this, let's discuss what tags are required on the OpenTracing side.
