### ISSUE TITLE
InjectOutboundSpan panics with NoopTracer

### ISSUE THREAD

**Issue by kriskowal** [uber/tchannel-go#527]
InjectOutboundSpan should not panic if provided an alternate tracer implementation.

See https://github.com/uber/jaeger-client-go/issues/56

**Comment by yurishkuro** [comment]
@kriskowal do you have a stacktrace, by chance? Note that most unit tests in this repo are run with default (Noop) tracer without issues.

**Comment by kriskowal** [comment]
Dug deeper. Trace led elsewhere.
