### ISSUE TITLE
relay: Cap TTL to some configurable max

### ISSUE THREAD

**Issue by prashantv** [uber/tchannel-go#529]
Allow a configurable TTL when creating a relay that is the maximum TTL that muttley supports. Hyperbahn currently uses a 2 minute cap on TTL, we should have something similar.

All calls with a TTL higher than this value should be capped (Muttley will change the `ttl` field).

We may want to track when we capped a TTL in stats so we can reach out to service owners and have them reduce their timeouts.

**Comment by akshayjshah** [comment]
Closed in #530.
