### ISSUE TITLE
Leave dependencies unpinned instead of pinning to master

### ISSUE THREAD

**Issue by akshayjshah** [uber/tchannel-go#646]
Imagine my surprise when, debugging some internal code, I realized that *we're* the ones pinning a bunch of dependencies to `master`!

If I recall, we started doing this a long time ago to cope with version conflicts. I don't think it's necessary anymore - should we instead leave these dependencies unpinned, so that service owners can choose the semver range they'd like to use?

**Comment by prashantv** [comment]
Our Glide manifest is a bit of a mess, there's a few things that need to be done:
 * Clearly separate `imports` and `testImports`.
 * Use semver ranges where possible, and unpin the others
 * Remove dependencies that are not strictly necessary in prod code (e.g., perhaps we shouldn't use `testify` in the `testutils` directory)

We can start with the first 2, and the last one can be done more gradually.
