### ISSUE TITLE
Getting error with master branch 

### ISSUE THREAD

**Issue by jayeshkhairnar** [uber/tchannel-go#648]
`*metaProcessorHealth does not implement thrift.TProcessorFunction (wrong type for Process method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
src/github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:290: cannot use metaProcessorThriftIDL literal (type *metaProcessorThriftIDL) as type thrift.TProcessorFunction in assignment:
        *metaProcessorThriftIDL does not implement thrift.TProcessorFunction (wrong type for Process method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
src/github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:291: cannot use metaProcessorVersionInfo literal (type *metaProcessorVersionInfo) as type thrift.TProcessorFunction in assignment:
        *metaProcessorVersionInfo does not implement thrift.TProcessorFunction (wrong type for Process method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
src/github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:301: not enough arguments in call to processor.Process
        have (int32, thrift.TProtocol, thrift.TProtocol)
        want (context.Context, int32, thrift.TProtocol, thrift.TProtocol)`

I am getting above error with master branch

**Comment by prashantv** [comment]
Apache Thrift has been pinned to 0.10.0, which does not pass the context argument.

Are you trying to use TChannel with the latest master of Apache Thrift? We don't have plans to make breaking changes to TChannel-Go, and instead are focusing on using Thrift through https://github.com/thriftrw/thriftrw-go
