### ISSUE TITLE
GC peers with no open connections

### ISSUE THREAD

**Issue by prashantv** [uber/tchannel-go#65]
Currently, even if a peer has no connections, it remains in memory forever.

We should GC peers that have no open connections.

**Comment by junchaowu** [comment]
How much memory that a peer will take ?

**Comment by prashantv** [comment]
It doesn't take much (probably on the order of 16-32 bytes), but tcurl does health checks constantly (like every second), so this can end up leaking a lot of memory.

The short term easier fix is tracked in #66.

**Comment by junchaowu** [comment]
Can we keep the original peers from hosts.json no matter what

**Comment by chucknthem** [comment]
@junchaowu I was seeing memory increases of about 1mb per hour from health checks.

**Comment by prashantv** [comment]
Peers with no open connections and no references (e.g. not in any peer list) are cleaned up as of #67)
