### ISSUE TITLE
server.go failed to start in example code

### ISSUE THREAD

**Issue by fengwfrank** [uber/tchannel-go#656]
Hi there, I just cloned the keyvalue example and compiled successfully. When I run the server.go, it gave me the below error msg. I wish I could get some help of how to fix this. Thank you.

# github.com/uber/tchannel-go/thrift/gen-go/meta
../../../github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:289:31: cannot use metaProcessorHealth literal (type *metaProcessorHealth) as type thrift.TProcessorFunction in assignment:
	*metaProcessorHealth does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
../../../github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:290:34: cannot use metaProcessorThriftIDL literal (type *metaProcessorThriftIDL) as type thrift.TProcessorFunction in assignment:
	*metaProcessorThriftIDL does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
../../../github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:291:36: cannot use metaProcessorVersionInfo literal (type *metaProcessorVersionInfo) as type thrift.TProcessorFunction in assignment:
	*metaProcessorVersionInfo does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
../../../github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:301:27: not enough arguments in call to processor.Process
	have (int32, thrift.TProtocol, thrift.TProtocol)
	want (context.Context, int32, thrift.TProtocol, thrift.TProtocol)

**Comment by prashantv** [comment]
TChannel doesn't support the latest version of Thrift, see the glide.yaml:
https://github.com/uber/tchannel-go/blob/dev/glide.yaml#L11

```
- package: github.com/apache/thrift
  version: '>=0.9.3, <0.11.0'
```

If you install that version of Thrift using `glide install` in the `tchannel-go` directory, it should work fine.
