### ISSUE TITLE
Update logs to avoid formatting strings

### ISSUE THREAD

**Issue by prashantv** [uber/tchannel-go#76]
Logs should only use `LogFields` to pass parameters -- the messages should be constant strings.

**Comment by akshayjshah** [comment]
I'll take this on tomorrow - I really want Moe's Sentry buckets to be better.

**Comment by akshayjshah** [comment]
Three-step process:

- [ ] Expand the `Logger` interface to support `Debug`, `Info`, et al.
- [ ] Migrate all logging to use fields instead of string substitution.
- [ ] Remove the `Debugf`, `Infof`, et al. from `Logger`.
