### ISSUE TITLE
what replaces hyperbahn. examples need updating?

### ISSUE THREAD

**Issue by zebralight** [uber/tchannel-go#765]
As I was going through this guide: https://github.com/uber/tchannel-go/blob/dev/guide/Thrift_Hyperbahn.md , I noticed that hyperbahn is no longer in active development as of 2016. Does this mean that there's a replacement that I should be aware of for broadcasting the service?  I also noticed that running https://github.com/uber/tchannel-go/tree/dev/examples/thrift issues these errors (abbreviated):
```
2020/02/23 16:01:07 secondHandler: Test()
2020/02/23 16:01:07 first: Echo(Hi)
2020/02/23 16:01:07 Echo(Hi) =  Hi , err:  <nil>
2020/02/23 16:01:07 first: AppError()
2020/02/23 16:01:07 AppError() =  tchannel error ErrCodeUnexpected: app error
2020/02/23 16:01:07 first: BaseCall()
2020/02/23 16:01:07 BaseCall() =  <nil>
2020/02/23 16:01:07 secondHandler: Test()
2020/02/23 16:01:07 first: Echo(Hi)
2020/02/23 16:01:07 Echo(Hi) =  Hi , err:  <nil>
2020/02/23 16:01:07 first: AppError()
2020/02/23 16:01:07 AppError() =  tchannel error ErrCodeUnexpected: app error
2020/02/23 16:01:07 first: BaseCall()
2020/02/23 16:01:07 BaseCall() =  <nil>
```

**Comment by prashantv** [comment]
We no longer rely on the service to broadcast where it's running itself, but instead rely on a cluster scheduler (e.g., Mesos) to announce this information into our service discovery platform.

The cluster scheduler is out of scope for documenting in tchannel-go, as it's a larger platform including Compute / Service Discovery, and is orthogonal to the wire protocol.
