### ISSUE TITLE
New release failing the build on zanzibar

### ISSUE THREAD

**Issue by zeeshan-mohd** [uber/tchannel-go#889]
Hi team , the latest release v1.32.1 is failing the build on [zanzibar](https://github.com/uber/zanzibar) , while going back to previous version the ci-build passes.
Could you please help in understanding what can be the issue here ? Does it need some changes from zanzibar ?
Here are two ci build link the first which is failing and the latter which uses an older version which is passing 
https://github.com/uber/zanzibar/actions/runs/3112435645 -> fails
https://github.com/uber/zanzibar/actions/runs/3167684254 -> passed after downgrading to 1.32.0

https://github.com/uber/zanzibar/pull/823 -> another PR that has build failing , changes are unrelated . The build is failing because one of the unit tests is getting stuck which is dependent on tchannel-go.

**Comment by cinchurge** [comment]
have you checked WHY it's failing? based on the logs it looks like it's [failing at grep](https://github.com/uber/zanzibar/actions/runs/3112435645/jobs/5159571754#step:14:203):
```
grep: write error: Resource temporarily unavailable
```
which is unlikely caused by any change to tchannel.
