### ISSUE TITLE
Embed mutexes rather than having them as a separate field

### ISSUE THREAD

**Issue by prashantv** [uber/tchannel-go#96]
Right now, some mutexes are embedded, while others typically use `mu` as the name. We should embed all mutexes and be consistent.

**Comment by akshayjshah** [comment]
@prashantv This is a pretty trivial fix, so I'm going to tackle this first. From what I can see, the following structs need their mutexes embedded:

- [ ] RecordingFramePool
- [ ] lockedSource
- [ ] NowStub
- [ ] Channel.mutable
- [ ] handlerMap
- [ ] messageExchangeSet
- [ ] subChannelMap
- [ ] thrift/Server
- [ ] kvHandler (x2)

Prashant, what do you think about these two? They appear to be a bit more idiomatic - the mutex protects just a few fields.
- [ ] [Connection](https://github.com/uber/tchannel-go/blob/master/connection.go#L143)
- [ ] [Peer](https://github.com/uber/tchannel-go/blob/master/peer.go#L228)

**Comment by prashantv** [comment]
@akshayjshah Cool, I have a branch with some work I did on this:
https://github.com/uber/tchannel-go/compare/mutex?expand=1

You might want to take over from there. Agree that Connection should stay as it is (since it only protects one field). I changed Peer though, since it protects a few fields (the 2 connection lists and the onUpdated hook).
